gsap.from('nav', { y: '-100%', duration: 1,  ease: "power1.Out" })
gsap.from('nav', {duration: 1.3, opacity:0 })
gsap.from('.navbar-brand', {duration: 1.5, delay: 0.7, opacity: 0 })
gsap.from('.nav-item', { delay: 0.9, opacity:0, duration: 1 })
gsap.from('#Background', { scale: 1.05, duration: 1.4, opacity:0.5, ease: 'power1.inOut' })
gsap.from('#wpp-button', {opacity: 0, duration: 1.4} )

gsap.from('.card-gsap', { y: 50, opacity: 0, duration: 1.2, stagger: 0.25, delay: 0.4, ease: 'power1.inout' })
gsap.from('#estudia', { y: -20,  opacity: 0, duration: 1.2, ease: 'power1.InOut'  })
gsap.from('footer', { y: 200, opacity: 0, duration: 1.2, stagger: 0.25, delay: 0.4, ease: 'power1.inout' })
